# Generated by Django 4.0.3 on 2022-04-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='USUÁRIO')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('enrollment', models.CharField(max_length=14, verbose_name='MATRÍCULA')),
                ('email', models.EmailField(max_length=70, verbose_name='E-MAIL')),
                ('phone', models.CharField(max_length=15, verbose_name='TELEFONE')),
            ],
        ),
    ]
