# Generated by Django 4.0.3 on 2022-04-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='MODELO')),
                ('brand', models.CharField(max_length=100, verbose_name='MARCA')),
                ('plate', models.CharField(max_length=100, verbose_name='PLACA')),
                ('color', models.CharField(max_length=100, verbose_name='COR')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.user')),
            ],
        ),
    ]
